version: "3"
services:
  idiom:
    container_name: idiom-server
    build: ./docker
    # image: sirly/idiom:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      redis: { condition: service_healthy }
      mysql: { condition: service_healthy }
      mongodb: { condition: service_started }

  redis:
    container_name: idiom-redis
    image: redis:alpine
    restart: always    
    volumes:
      - ./redis/config:/etc/redis
      - ./redis/data:/data
      - ./redis/logs:/logs
    # command: /etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s

  mongodb:
    container_name: idiom-mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo/data/:/data/db

  mysql:
    container_name: idiom-mysql
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: 
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_HOST: mysql
      MYSQL_DATABASE: idiom
      MYSQL_USER: idiom
      MYSQL_PASSWORD: idiom
      MYSQL_ROOT_PASSWORD: kqnmUcWD94FbHTeNwWbo
    healthcheck:
      test: mysqladmin ping -h $$MYSQL_HOST -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 10s
      interval: 5s
      timeout: 1s